config/routes.rb
Rails.application.routes.draw do
  resources :trades do
    member do
      post :close
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/admin", to: "admins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :timeoutable, :trackable
  has_many :trades
end

app/controllers/admins_controller.rb
require "finnhub_ruby"

# admin controller
class AdminsController < ApplicationController
  FinnhubRuby.configure do |config|
    config.api_key["token"] = "c3psf32ad3ifkq8h5du0"
  end

  FINNHUB_CLIENT = FinnhubRuby::DefaultApi.new

  def index
    @users = User.all
    puts AdminsController::FINNHUB_CLIENT.quote("AAPL")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# home controller
class HomeController < ApplicationController
  def index
    @content = User.all.inspect
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trade, only: %i[ show edit update destroy close ]

  # GET /trades or /trades.json
  def index
    @trades = Trade.where(user_id: current_user.id)
  end

  # GET /trades/1 or /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # GET /trades/1/close
  # close this position
  def close
    @trade.close_date = now
    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: "This position was successfully closed." }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end

  end

  # POST /trades or /trades.json
  def create
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: "Trade was successfully created." }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1 or /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: "Trade was successfully updated." }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1 or /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url, notice: "Trade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trade
    @trade = Trade.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def trade_params
    params.require(:trade).permit(:trade_type, :symbol, :open_price, :close_price, :open_date, :close_date)
          .merge(user_id: current_user.id)
  end

  def now
    DateTime.now
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finnhub_helper.rb
require "finnhub_ruby"

module FinnhubHelper
  FinnhubRuby.configure do |config|
    config.api_key["token"] = "c3psf32ad3ifkq8h5du0"
  end

  @@finnhub_client = FinnhubRuby::DefaultApi.new
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/admins/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Created at</th>
      <th scope="col">Updated at</th>
      <th scope="col">Last sign in at</th>
      <th scope="col">Sign in count</th>
      <th scope="col">Last sign in IP</th>
      <th scope="col">Current sign in IP</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= user.current_sign_in_ip %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
  <%= @content %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TechStackApp</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <%= render partial: "shared/navbar" %>
  <div class="container">
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>

</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">THETA GANG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/trades">Trades</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/admin">Admin management</a>
        </li>
      </ul>
      <% if user_signed_in? %>
      Logged in as: <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-light' %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-light'  %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-light'  %>
      <%= link_to "Login", new_user_session_path, :class => 'btn btn-light'  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/trades/_form.html.erb
<%= form_with(model: trade) do |form| %>
  <% if trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
        <% trade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :trade_type, "Call/Put" %>
    <%= form.text_field :trade_type, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :open_price %>
    <%= form.text_field :open_price, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :close_price %>
    <%= form.text_field :close_price, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :open_date %>
    <%= form.datetime_select :open_date %>
  </div>

  <div class="field form-group">
    <%= form.label :close_date %>
    <%= form.datetime_select :close_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Trade type</th>
      <th scope="col">Symbol</th>
      <th scope="col">Open price</th>
      <th scope="col">Close price</th>
      <th scope="col">Open date</th>
      <th scope="col">Close date</th>
      <th scope="col" colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.trade_type %></td>
        <td><%= trade.symbol %></td>
        <td><%= trade.open_price %></td>
        <td><%= trade.close_price %></td>
        <td><%= trade.open_date %></td>
        <td><%= trade.close_date %></td>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Close trade', close_trade_path(trade), method: :post, data: { confirm: 'Are you sure to close this position?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Call or Put:</strong>
  <%= @trade.trade_type %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @trade.symbol %>
</p>

<p>
  <strong>Open price:</strong>
  <%= @trade.open_price %>
</p>

<p>
  <strong>Close price:</strong>
  <%= @trade.close_price %>
</p>

<p>
  <strong>Open date:</strong>
  <%= @trade.open_date %>
</p>

<p>
  <strong>Close date:</strong>
  <%= @trade.close_date %>
</p>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>